# Read the Docs configuration file
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: module_4/docs/source/conf.py

# Build with Python 3.10 to match your local environment
python:
  install:
    - requirements: module_4/requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"